# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms
# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-githubs-form-schema
# https://learnxinyminutes.com/docs/yaml/
---
name: Feature request
description: Suggest an idea for this project
title: '[rfe]: '
labels: ["feature", "triage"]
assignees:
  - avisiedo
  - little-engineer-2025
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill a feature request!
  - type: textarea
    attributes:
      label: Describe the feature
      value: |
        as a ROLE I want SUMMARIZE THE FEATURE that meet with:
        - When I run with ... I get ...
        - When I run with ... I get ... and ... and ...

        **Additional context**
        Add any other context or screenshots about the feature request here.
      placeholder: add information about the feature and rationale it
    validations:
      required: true

